---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: payments-deploy
    namespace: node-ticketing
spec:
    replicas: 1
    selector:
        matchLabels:
            app: payments
    template:
        metadata:
            labels:
                app: payments
        spec:
            containers:
            - name: payments
              image: 192.168.1.59:5000/ticketing_payments:latest
              env:
                - name: NATS_CLIENT_ID
                  valueFrom: 
                    fieldRef:
                        fieldPath: metadata.name
                - name: NATS_URL
                  value: 'http://natss-svc:4222' 
                - name: NATS_CLUSTER_ID
                  value: ticketing
                - name: MONGO_URI
                  value: 'mongodb://payments-mongo-svc/payments'
                - name: JWT_KEY
                  valueFrom:
                    secretKeyRef:
                        name: jwt-secret
                        key: JWT_KEY
                - name: STRIPE_KEY
                  valueFrom:
                    secretKeyRef:
                        name: ticketing-stripe-secret
                        key: STRIPE_KEY

---
apiVersion: v1
kind: Service
metadata:
    name: payments-svc 
    namespace: node-ticketing
spec:
    type: ClusterIP
    selector:
        app: payments
    ports:
    - name: payments
      protocol: TCP
      port: 3000
      targetPort: 3000